# Drone CI Pipeline for nbin

## AMD64 Pipeline - Master Build Test
kind: pipeline
type: docker
name: build-master-amd64

platform:
  arch: amd64

steps:

- name: build
  image: ubuntu
  commands:
    - sudo apt update && sudo apt install -y build-essential ccache
    - yarn
    - yarn build

---
## ARM64 - Master Build Test
kind: pipeline
type: docker
name: build-master-arm64

platform:
  arch: arm64

steps:

- name: build
  image: ubuntu
  commands:
    - sudo apt update && sudo apt install -y build-essential ccache
    - yarn
    - yarn build

---
## ARM - Master Build Test
kind: pipeline
type: docker
name: build-master-arm

platform:
  arch: arm

steps:

- name: build
  image: ubuntu
  commands:
    - sudo apt update && sudo apt install -y build-essential ccache
    - yarn
    - yarn build

---
## AMD64 - Release
kind: pipeline
type: docker
name: rel-amd64

platform:
  arch: amd64

steps:

- name: build
  image: ubuntu
  commands:
    - sudo apt update && sudo apt install -y build-essential ccache
    - yarn
    - yarn build

- name: deploy
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token

trigger:
  branch:
  - master
  event:
  - tag

---
## ARM64 - Release
kind: pipeline
type: docker
name: rel-arm64

platform:
  arch: arm64

steps:

- name: build
  image: ubuntu
  commands:
    - sudo apt update && sudo apt install -y build-essential ccache
    - yarn
    - yarn build

- name: deploy
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token

trigger:
  branch:
  - master
  event:
  - tag

---
## ARM - Release
kind: pipeline
type: docker
name: rel-arm

platform:
  arch: arm

steps:

- name: build
  image: ubuntu
  commands:
    - sudo apt update && sudo apt install -y build-essential ccache
    - yarn
    - yarn build

- name: deploy
  image: plugins/gcs
  settings:
     source: build/
     target: nbin.cdr.sh
     token:
       from_secret: gcs-token

trigger:
  branch:
  - master
  event:
  - tag