name: Build
on:
  push:
    branches:
       - 'sr229/docker-xbuild'
       - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Docker Edge Build (for Xbuild runs)
        run: wget -qO - https://test.docker.com | sh
      
      - name: Setup Builder instance
        run: |
            export DOCKER_CLI_EXPERMIENTAL=enabled
            docker buildx create --name cdr-build
            docker buildx use cdr-build
            docker buildx inspect --bootstrap
          