name: Build Docker images
on:
  push:
    branches:
       - 'sr229/docker-xbuild'
       - 'master'

jobs:
  build_arm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Docker Edge Build (for Xbuild runs)
        run: wget -qO - https://test.docker.com | sh
      
      - name: Install buildx
        run: |
          mkdir -p  $HOME/.docker/cli-plugins/
          touch $HOME/.docker/cli-plugins/docker-buildx
          wget -qO - https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 > $HOME/.docker/cli-plugins/docker-buildx
          chmod a+x $HOME/.docker/cli-plugins/docker-buildx
      
      - name: Setup Builder instance
        run: |
            export DOCKER_CLI_EXPERMIENTAL=enabled
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker buildx create --name cdr-build
            docker buildx use cdr-build
            docker buildx inspect --bootstrap
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      
      - name: Build Images - ARM64 (CentOS)
        run: |
           export DOCKER_CLI_EXPERMIENTAL=enabled
           docker buildx build --platform linux/arm64 -t codercom/nbin-centos:arm64 -f centos.dockerfile .

      - name: Build Images - ARM (CentOS)
        run: |
           export DOCKER_CLI_EXPERMIENTAL=enabled
           docker buildx build --platform linux/arm -t codercom/nbin-centos:arm -f centos.dockerfile .
      
      - name: Build Images - ARM64 (Alpine)
        run: |
           export DOCKER_CLI_EXPERMIENTAL=enabled
           docker buildx build --platform linux/arm64 -t codercom/nbin-alpine:arm64 -f alpine.dockerfile .

      - name: Build Images - ARM (Alpine)
        run: |
           export DOCKER_CLI_EXPERMIENTAL=enabled
           docker buildx build --platform linux/arm -t codercom/nbin-alpine:arm -f alpine.dockerfile .

  build_amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install Docker Edge Build (for Xbuild runs)
        run: wget -qO - https://test.docker.com | sh

      - name: Install buildx
        run: |
          mkdir -p  $HOME/.docker/cli-plugins/
          touch $HOME/.docker/cli-plugins/docker-buildx
          wget -qO - https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 > $HOME/.docker/cli-plugins/docker-buildx
          chmod a+x $HOME/.docker/cli-plugins/docker-buildx
      
      - name: Setup Builder instance
        run: |
            export DOCKER_CLI_EXPERMIENTAL=enabled
            docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
            docker buildx create --name cdr-build
            docker buildx use cdr-build
            docker buildx inspect --bootstrap

      - name: Build Images - AMD64 (CentOS)
        run: |
          export DOCKER_CLI_EXPERMIENTAL=enabled
          docker buildx build --platform linux/amd64 -t codercom/nbin-centos:amd64 -f centos.dockerfile .
      
      - name: Build Images - AMD64 (Alpine)
        run: |
         export DOCKER_CLI_EXPERMIENTAL=enabled
         docker buildx build --platform linux/amd64 -t codercom/nbin-alpine:amd64 -f alpine.dockerfile .